Flutter/3 lab
nazarovnh/fkn_labs_2022 pull request #3
Opened 2022-11-17 13:31 UTC by nazarovnh

2022-11-20 17:08 UTC, rvachev requested changes

2022-11-20 17:08 UTC, rvachev commented on marvel_herous/lib/api/fetcher.dart
> +}
вообще так не очень хорошо делать, так как такой метод имеет глобальную видимость в проекте. Обычно для них создается класс `ApiClient`

2022-11-20 17:08 UTC, rvachev commented on marvel_herous/lib/api/request/getAllHeroes.dart
> +          .forEach((value) => result.add(value['id'])));
нет смысла использовать `await` и `then` одновременно. `then` мы используем когда хотим выполнить какие-нибудь действия после выполнения асинхронного метода без ожидания его окончания. но если ты используешь `await`, то `then` необязательно и их одновременное использование противоречит друг другу

2022-11-20 17:08 UTC, rvachev commented on marvel_herous/lib/api/request/getAllHeroes.dart
> +          .forEach((value) => result.add(value['id'])));
для такого рода преобразований нужно использовать метод `map`, а не `foreach`

2022-11-20 17:08 UTC, rvachev commented on marvel_herous/lib/presentation/controllers/page_controller.dart
> +            }));
перерисовывать экран на каждую итерацию - не очень целесообразно, это нужно сделать единожды после отработки всего цикла

2022-11-24 05:58 UTC, nazarovnh commented on marvel_herous/lib/api/request/getAllHeroes.dart
> +          .forEach((value) => result.add(value['id'])));
Разве `then` не вызывается после успешного выполнения и ожидает выполнение асинхронного метода?

2022-11-24 06:44 UTC, rvachev commented on marvel_herous/lib/api/request/getAllHeroes.dart
> +          .forEach((value) => result.add(value['id'])));
`then` вызывается после успешного выполнения `Future` метода, правильно. Но в сочетании с `await` это имеет смысла.
Эквивалентная запись
```
final response = await fetch(
          'https://gateway.marvel.com:443/v1/public/characters?limit=$limitHeroes&offset=$offset&');
for(final result in response.data['data']['results']){
  result.add(value['id']);
}
```

2022-11-24 06:50 UTC, nazarovnh commented on marvel_herous/lib/api/request/getAllHeroes.dart
> +          .forEach((value) => result.add(value['id'])));
Да, я понял вашу, мысль и согласен, в первый раз чушь написал. Просто вы в первом комментарии написали

>  `then` мы используем когда хотим выполнить какие-нибудь действия после выполнения асинхронного метода без ожидания его окончания

Я просто знаю, что в JS then выполняется только после успешного выполнение Promise. Я думал тут также только после успешного выполнения асинхронного метода, но почему-то он у меня не дожидается ответа :)
Поэтому использовал await в последних коммитах

2022-11-24 07:23 UTC, rvachev approved these changes
можно мержить. Все три лабы сданы, следовательно, зачет

2022-11-24 07:36 UTC, merged